export const COLORS=["cyan","violet","rose","gold","mint","ember"];
export const LEVELS=Array.from({length:20},(_,i)=>{const n=i+1;return{level:n,chapter:n<=5?"The First Rift":n<=10?"Prism Gallery":n<=15?"Moonlit Archive":"Astral Foundry",colors:Math.min(6,3+Math.floor(i/4)),triples:Math.min(14,4+Math.floor(i*.55)),slots:n<=3?6:5,columns:n<=2?4:n<=8?5:6,tutorial:n===1?"Make a triple. Only glowing crystals can move.":n===4?"The belt now has five slots. Plan ahead.":n===9?"Hints protect your streak, but cost a charge.":"Tap any exposed crystal."}});
export function seededRandom(seed){let value=seed>>>0;return()=>{value+=0x6d2b79f5;let n=value;n=Math.imul(n^n>>>15,n|1);n^=n+Math.imul(n^n>>>7,n|61);return((n^n>>>14)>>>0)/4294967296}}
export function createLevel(config,seed=1733+config.level*7919){const random=seededRandom(seed),groups=Array.from({length:config.triples},(_,i)=>i%config.colors);for(let i=groups.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[groups[i],groups[j]]=[groups[j],groups[i]]}const solution=groups.flatMap(c=>[c,c,c]),removalQueues=Array.from({length:config.columns},()=>[]),solutionMoves=[];for(const color of solution){const candidates=removalQueues.map((s,index)=>({index,size:s.length+random()*1.4})).sort((a,b)=>a.size-b.size),index=candidates[0].index;removalQueues[index].push(color);solutionMoves.push(index)}const stacks=removalQueues.map(queue=>queue.reverse());return{stacks,solution,solutionMoves}}
export function snapshot(s){return{stacks:s.stacks.map(x=>[...x]),tray:[...s.tray],cleared:s.cleared,combo:s.combo,score:s.score,moves:s.moves}}
export function takeCrystal(state,stackIndex){if(state.status!=="playing"||!state.stacks[stackIndex]?.length)return state;const previous=snapshot(state),stacks=state.stacks.map(s=>[...s]),color=stacks[stackIndex].pop(),tray=[...state.tray,color],matching=tray.reduce((a,v,i)=>v===color?[...a,i]:a,[]);let cleared=state.cleared,combo=1,score=state.score+10*state.combo;if(matching.length>=3){const remove=new Set(matching.slice(-3));tray.splice(0,tray.length,...tray.filter((_,i)=>!remove.has(i)));cleared+=3;combo=Math.min(8,state.combo+1);score+=60*state.combo}const remaining=stacks.reduce((n,s)=>n+s.length,0),status=remaining===0&&tray.length===0?"won":tray.length>=state.slots?"lost":"playing";return{...state,stacks,tray,cleared,combo,score,status,history:[...state.history,previous],moves:state.moves+1}}
export function undo(state){if(!state.boosters.undo||!state.history.length||state.status!=="playing")return state;const previous=state.history.at(-1);return{...state,...previous,status:"playing",history:state.history.slice(0,-1),boosters:{...state.boosters,undo:state.boosters.undo-1},toolsUsed:state.toolsUsed+1}}
export function bestMove(state){const counts=state.tray.reduce((o,c)=>({...o,[c]:(o[c]||0)+1}),{});return state.stacks.reduce((best,stack,index)=>{if(!stack.length)return best;const color=stack.at(-1),score=(counts[color]||0)*10+state.stacks.filter(s=>s.at(-1)===color).length;return!best||score>best.score?{index,color,score}:best},null)}
export function initialState(config){const generated=createLevel(config);return{...generated,level:config.level,slots:config.slots,tray:[],history:[],score:0,combo:1,cleared:0,moves:0,toolsUsed:0,status:"playing",boosters:{undo:1,hint:2,extra:1}}}
